//ADDSUB_MACRO:Variablewidth&latency-Adder/SubtracterimplementedinaDSP48E
//
7Series
//XilinxHDLLibrariesGuide,version2015.2
ADDSUB_MACRO#(
.DEVICE("7SERIES"),//TargetDevice:"7SERIES"
.LATENCY(2),//Desiredclockcyclelatency,0-2
.WIDTH(8)
//Input/outputbuswidth,1-48
)ADDSUB_MACRO_inst(
.CARRYOUT(CARRYOUT),//1-bitcarry-outoutputsignal
.RESULT(RESULT),//Add/subresultoutput,widthdefinedbyWIDTHparameter
.A(A),
//InputAbus,widthdefinedbyWIDTHparameter
.ADD_SUB(ADD_SUB),//1-bitadd/subinput,highselectsadd,lowselectssubtract
.B(B),
//InputBbus,widthdefinedbyWIDTHparameter
.CARRYIN(CARRYIN),//1-bitcarry-ininput
.CE(CE),
//1-bitclockenableinput
.CLK(CLK),
//1-bitclockinput
.RST(RST)
//1-bitactivehighsynchronousreset
);
//EndofADDSUB_MACRO_instinstantiation
